FROM mcc.py:0.1

WORKDIR /tests

RUN mkdir output

COPY ./requirements.txt /requirements.txt

RUN pip install --no-cache-dir --upgrade pip==23.3.1 \
 && pip install --no-cache-dir -r /requirements.txt

COPY ./MCCRobotLibrary.py ./

COPY ./TestLibrary.robot ./

COPY ./TestCommands.robot ./

COPY ./commands_test_data.json ./

CMD [ "python", "-m", "robot", "-d", "./output", "./TestCommands.robot"]
