name: 'Test Report'
on:
  workflow_run:
    workflows: ['Publish']
    types:
      - completed
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: py-unit-test-results
        name: Pytest results
        path: '*.xml'
        reporter: java-junit
    - uses: dorny/test-reporter@v1
      with:
        artifact: robot-test-results
        name: Robot results
        path: /tests/output/xunit.xml
        reporter: java-junit
